### ISSUE TITLE
Waveform generation

### ISSUE THREAD

**Issue by OrkoHunter** [morse-talk/morse-talk#10]
Checkout [PySynth](https://github.com/mdoege/PySynth) for waveform generation.

**Comment by kshitij10496** [comment]
Maybe, we can integrate that in a future version ?

**Comment by OrkoHunter** [comment]
+1

**Comment by kshitij10496** [comment]
Lets complete the decoding module and then we can try in KGP !

**Comment by OrkoHunter** [comment]
Fine by me!

Himanshu Mishra

**Comment by s-celles** [comment]
I did some work to make a generator it's available at https://github.com/scls19fr/cw

The main idea is that I'm working only with binary representation.
We can count consectives "1", consecutives "0", consecutive "1" ...

```
pi@raspberrypi ~/github/scls19fr/cw $ python morse_code_gen.py --msg "SOS"
DEBUG:__main__:SOS
DEBUG:__main__:...   ---   ...
DEBUG:__main__:101010001110111011100010101
DEBUG:__main__:[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1] (this is just a list for "reference")
DEBUG:__main__:[1, 1, 1, 1, 1, 3, 3, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1]
101010001110111011100010101

pi@raspberrypi ~/github/scls19fr/cw $ python morse_code_gen.py --msg "MORSE CODE"
DEBUG:__main__:MORSE CODE
DEBUG:__main__:--   ---   .-.   ...   .       -.-.   ---   -..   .
DEBUG:__main__:11101110001110111011100010111010001010100010000000111010111010001110111011100011101010001
DEBUG:__main__:[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
DEBUG:__main__:[3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 7, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1]
11101110001110111011100010111010001010100010000000111010111010001110111011100011101010001
```

We can clearly see 3 "1", 1 "0", 3 "1", 3 "0", 3 "1"
I just printing to stdout so we get exactly same bits as with input

(I should probably make a unit test)

I made some  experiments with a Raspberry Pi and GPIO (a led) with Pingo 
https://github.com/pingo-io/pingo-py/

(sorry no sound)

```
pi@raspberrypi ~/github/scls19fr/cw $ python lightning_morse_pingo.py --msg "SOS"
Using RaspberryPi 2 Model B...
/usr/local/lib/python2.7/dist-packages/pingo-0.2.0-py2.7.egg/pingo/rpi/rpi.py:71: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
DEBUG:morse_code_gen:101010001110111011100010101
DEBUG:morse_code_gen:[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
DEBUG:morse_code_gen:[1, 1, 1, 1, 1, 3, 3, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1]

pi@raspberrypi ~/github/scls19fr/cw $ python lightning_morse_pingo.py --msg "MORSE CODE"
Using RaspberryPi 2 Model B...
/usr/local/lib/python2.7/dist-packages/pingo-0.2.0-py2.7.egg/pingo/rpi/rpi.py:71: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
DEBUG:morse_code_gen:11101110001110111011100010111010001010100010000000111010111010001110111011100011101010001
DEBUG:morse_code_gen:[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
DEBUG:morse_code_gen:[3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 7, 3, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 1, 1, 3, 1]
```

So led is blinking accordingly.

I made this code with inheritance.
you just need to overload `on` and `off` methods

it's probably also possible to make it without working with binary representation.

**Comment by s-celles** [comment]
For sound generation

I think that PySynth is overskilled for our work... we just want to generate a sine wave (with a frequency around 550-850 Hz) and silent!

Moreover PySynth doesn't seems to be available for Python 3.

You should find some inspiration here:
https://github.com/cardre/morsewav.py/blob/master/morsewav.py
https://github.com/docwhat/morse-python

Unfortunately audiodev was removed in Python 3 but there is `wave`
https://docs.python.org/3/library/wave.html

This article is interesting
https://zach.se/generate-audio-with-python/
This guy did `wavebender`
https://github.com/zacharydenton/wavebender/blob/master/wavebender/__init__.py

Caution with Python 3 you have to use `range` not `xrange` (we will need a `compat.py` file)
