### ISSUE TITLE
Unit tests, continuous integration 

### ISSUE THREAD

**Issue by s-celles** [morse-talk/morse-talk#19]
Hello,

it will be nice to have some unit tests and continuous integration enabled.
Travis can help https://travis-ci.org/

Kind regards

**Comment by OrkoHunter** [comment]
Hello @scls19fr,
Yes, I remember when I was writing the unit tests and I recall due to some reasons the results were not same for Python 2 and 3.
Well, it's here https://travis-ci.org/OrkoHunter/morse-talk

**Comment by s-celles** [comment]
Ok but why do you use a separate branch for Travis ?

You should put it on master branch so you will see when a PR break your code

**Comment by OrkoHunter** [comment]
I didn't think it was ready to be merged at that time.
