### ISSUE TITLE
License MIT or GNU ? if GNU license ? which one ?

### ISSUE THREAD

**Issue by s-celles** [morse-talk/morse-talk#27]
Hello,

there's a problem with licenses.

in `setup.py` https://github.com/OrkoHunter/morse-talk/blob/master/setup.py
there is

```
    license='MIT',
```

but in source code we can find

```
#    Copyright (C) 2015 by
#    Himanshu Mishra <himanshu2014iit@gmail.com>
#    All rights reserved.
#    GNU license.
```

so is it MIT or GNU license ?

If it's a GNU license is it GPL or LPGL ?

Kind regards

**Comment by OrkoHunter** [comment]
hmm.. I didn't really didn't about the license. I think I'll stick with either MIT or BSD.

**Comment by s-celles** [comment]
GNU GPL vs (GNU LGPL, BSD, MIT) It depends if you want to allow your code be include in proprietary software.

If you choose GPL, code can't be include so it urge people to use a compatible license (not proprietary) if they want to use this lib.

You might have a look at http://choosealicense.com/
