### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by OrkoHunter** [morse-talk/morse-talk#34]
After the new features got added, we need to update the [documentation](http://morse-talk.readthedocs.org/) according to it. I'm on it.

**Comment by s-celles** [comment]
You might fix

http://morse-talk.readthedocs.org/overview.html

NetworkX is intended to provide

2015-11-29 19:10 GMT+01:00 Himanshu Mishra notifications@github.com:

**Comment by s-celles** [comment]
RTD have badge
I think you should also put it on README.md
