### ISSUE TITLE
CLI tools should be available when morse-talk package is installed

### ISSUE THREAD

**Issue by s-celles** [morse-talk/morse-talk#39]
Hello,

we have now some command line tools in morse-talk package.

Plot

```
$ python plot.py -m "SOS" -d 1
```

Sound

```
$ python sound.py -m "SOS" -s 15
```

Tree

```
$ python tree.py --c " -.-."
```

Maybe we should have in `setup.py` something like 

```
  scripts=['bin/mplot', 'bin/msound', 'bin/mtree'],
```

or any other method which could help to use morse-talk as CLI.

Kind regards

**Comment by s-celles** [comment]
Not sure how this PR will behave under Windows

**Comment by s-celles** [comment]
I saw in some other `setup.py`

```
# To provide executable scripts, use entry points in preference to the
# "scripts" keyword. Entry points provide cross-platform support and allow
# pip to create the appropriate form of executable for the target platform.
#entry_points={
#    'console_scripts': [
#        'sample=sample:main',
#    ],
#},
```

We might use this instead of `"scripts"` keyword

**Comment by OrkoHunter** [comment]
Yeah sure. I have already tried this one [here](https://github.com/OrkoHunter/ping-me/blob/master/setup.py#L27-L32) and it works fine.

**Comment by s-celles** [comment]
I forget to put unit tests for CLI.

```
from nose.tools import assert_raises

from morse_talk.cli_mtree import main as mtree
from morse_talk.cli_msound import main as msound
from morse_talk.cli_mplot import main as mplot

class TestCLI:
    def test_mtree(self):
        with assert_raises(SystemExit):
            mtree()

    def test_mplot(self):
        with assert_raises(SystemExit):
            mplot()

    def test_msound(self):
        with assert_raises(SystemExit):
            msound()
```

**Comment by OrkoHunter** [comment]
Landscape reports one error [here](https://github.com/morse-talk/morse-talk/blob/e7cc03520b0376082263c9c895c0715e559ade49/morse_talk/cli_msound.py#L63). I believe that should be `sys.stdout`.

**Comment by s-celles** [comment]
Fixed (directly into master). Sorry.

**Comment by OrkoHunter** [comment]
That's okay. It was just a tiny fix.
